//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpID { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public int Airport_Code { get; set; }
    
        public virtual Airport Airport { get; set; }
    }
}
