//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public int Flight { get; set; }
        public virtual Flight_Schedule Flight_Schedule { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
