//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.AirFares = new HashSet<AirFare>();
        }
    
        public int RtID { get; set; }
        public string Airport { get; set; }
        public string Destination { get; set; }
        public string RouteCode { get; set; }
    
        public virtual ICollection<AirFare> AirFares { get; set; }
    }
}
